apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{template "fullname" .}}
  labels:
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: {{ .Release.Service | quote }}
    # This makes it easy to search for all components of a release using kubectl.
    release: "v{{ template "image_tag" .}}"
    # This makes it easy to audit chart usage.
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: 1
  template:
    metadata:
      name: docker-demo-1
      labels:
        app: docker-demo-1
    spec:
      containers:
        - name: docker-demo-1
          image: jmeisner/docker-demo-1:{{ template "image_tag" .}}
          ports:
          - containerPort: 80
